
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"

if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init --path)"
  eval "$(pyenv init -)"
fi

eval "$(starship init zsh)"

export PATH="/opt/homebrew/opt/openjdk/bin:$PATH"
export PATH="/opt/homebrew/opt/openjdk@21/bin:$PATH"
export PATH="/opt/homebrew/opt/openjdk@17/bin:$PATH"

export EDITOR=nano

# --- Work: Atlan ---
# Uncomment the following on work machines

# Alias to temporarily add patlan to the PATH
# alias start_patlan='export PATH="$HOME/.local/bin:$PATH" && echo "Patlan CLI enabled!"'

# Alias to remove patlan from the PATH
# alias stop_patlan='export PATH=$(echo $PATH | sed -E "s|:$HOME/.local/bin||") && echo "Patlan CLI disabled!"'

# Alias for vcluster connect
# alias vc='vcluster platform connect vcluster'

# Alias for argopm install
# alias ap='argopm install . -n default -f -c'

# Heracles Go Env Variables
# export GO111MODULE=on
# export GOPRIVATE=github.com/atlanhq

export PATH="/usr/local/go/bin:$PATH"
[ -f "$HOME/.local/bin/env" ] && . "$HOME/.local/bin/env"

# --- Corporate: Netskope MDM ---
# Auto-uncommented by setup.sh if Netskope cert is detected
# export AWS_CA_BUNDLE="/Library/Application Support/ns_cert/nscacert_combined.pem"
# export CURL_CA_BUNDLE="/Library/Application Support/ns_cert/nscacert_combined.pem"
# export SSL_CERT_FILE="/Library/Application Support/ns_cert/nscacert_combined.pem"
# export GIT_SSL_CAPATH="/Library/Application Support/ns_cert/nscacert_combined.pem"
# export REQUESTS_CA_BUNDLE="/Library/Application Support/ns_cert/nscacert_combined.pem"
# export NODE_EXTRA_CA_CERTS="/Library/Application Support/ns_cert/nscacert_combined.pem"


# pnpm
export PNPM_HOME="$HOME/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end

# pnpm global bin directory
export PNPM_GLOBAL_BIN_DIR="$PNPM_HOME/global/5/node_modules/.bin"
case ":$PATH:" in
  *":$PNPM_GLOBAL_BIN_DIR:"*) ;;
  *) export PATH="$PNPM_GLOBAL_BIN_DIR:$PATH" ;;
esac
export PATH="/opt/homebrew/opt/go@1.21/bin:$PATH"
